
try {
    console.log("Hello");
    console.log(a);
    console.log("ending try");

} catch (error) {
    console.log("error handling in catch", error);
}
finally {
    console.log("Finally always gets executed");
}